Cn translation
moonbeam-foundation/moonbeam-docs-cn pull request #348
Opened 2023-10-17 06:42 UTC by wuzhong-papermoon

Translation for the following PR

https://github.com/moonbeam-foundation/moonbeam-docs/pull/761
https://github.com/moonbeam-foundation/moonbeam-docs/pull/720
https://github.com/moonbeam-foundation/moonbeam-docs/pull/756
https://github.com/moonbeam-foundation/moonbeam-docs/pull/755

2023-10-19 07:09 UTC, eshaben requested changes
Nice job! Just a couple minor things! 🙂 

For posterity's sake, just noting this one was not in the description, but was translated: https://github.com/moonbeam-foundation/moonbeam-docs/pull/749/files

2023-10-19 07:09 UTC, eshaben commented on builders/get-started/networks/moonbeam-dev.md
> +!!! note
```suggestion
!!! 注意事项
```

2023-10-19 07:09 UTC, eshaben commented on builders/get-started/networks/moonbeam-dev.md
> +
```suggestion
!!! 注意事项
    安装路径包含空格会造成编译错误
```

2023-10-19 07:09 UTC, eshaben commented
Also just noticed the merge conflicts, can you please resolve them @wuzhong-papermoon?

2023-10-23 05:31 UTC, wuzhong-papermoon commented on builders/build/substrate-api/polkadot-js-api.md
> +??? code "View the complete script"
```suggestion
??? code "查看完整文件"
```

2023-10-23 05:42 UTC, wuzhong-papermoon commented
Hi Erin! 
Thanks for taking the time to review this PR. All the suggested changes have been made.

2023-10-25 02:25 UTC, eshaben approved these changes
LGTM!

2023-10-25 02:25 UTC, merged